# Generated by Django 5.2.4 on 2025-08-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_date_alter_attendance_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='location',
            field=models.CharField(choices=[('Chennai Office', 'Chennai Office'), ('Noida Office', 'Noida Office'), ('Bangalore Office', 'Bangalore Office'), ('Work from Home', 'Work from Home')], default='Work from Home', max_length=50),
        ),
    ]
